### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by rajesh-rt** [tramvm/DemoFaceRecognize#1]
My current setup is as follows:

IDE : Eclipse
OpenCV : 2.4.11

I'm creating recognizer like this
FaceRecognizer recognizer = new FisherFaceRecognizerID();

public class FisherFaceRecognizerID extends FaceRecognizer{

	private static native long createFisherFaceRecognizer_1();

	private static native long createFisherFaceRecognizer_1(int num_components);

	private static native long createFisherFaceRecognizer_2(int num_components,
			double threshold);

	public FisherFaceRecognizerID() {
		super(createFisherFaceRecognizer_1());
	}

	public FisherFaceRecognizerID(int num_components) {
		super(createFisherFaceRecognizer_1(num_components));
	}

	public FisherFaceRecognizerID(int num_components, double threshold) {
		super(createFisherFaceRecognizer_2(num_components, threshold));
	}
}

I'm getting the below error:

Exception in thread "main" java.lang.UnsatisfiedLinkError: com.raj.opencv.facerecognizer.FisherFaceRecognizerID.createFisherFaceRecognizer_1()J
	at com.raj.opencv.facerecognizer.FisherFaceRecognizerID.createFisherFaceRecognizer_1(Native Method)
	at com.raj.opencv.facerecognizer.FisherFaceRecognizerID.<init>(FisherFaceRecognizerID.java:15)
	at com.raj.opencv.facerecognizer.FaceRecognizer1.createRecognizer(FaceRecognizer1.java:115)
	at com.raj.opencv.facerecognizer.FaceRecognizer1.cameraRecognize(FaceRecognizer1.java:45)
	at com.raj.opencv.facerecognizer.FaceRecognizer1.main(FaceRecognizer1.java:38)

Could you help me with this?

Thanks.

**Comment by tramvm** [comment]
Hello bro,

It is just config problem.
Please follow the video to have correct config https://youtu.be/8zjFofbsJGM
<https://youtu.be/8zjFofbsJGM>
And do not forget to subscribe my channel for more helpful video :)

Thanks & best regards,

Vo Minh Tram

**Comment by rajesh-rt** [comment]
I have added library path like you have shown in the video. But I still have this error:
Exception in thread "main" java.lang.UnsatisfiedLinkError: com.raj.opencv.facerecognizer.FisherFaceRecognizerID.createFisherFaceRecognizer_1()J

Its in the recognizer. Other features like cropping, resizing, face detection are working fine.

Does this has anything to do with the openCV version?
I'm using openCV-2.4.11 by the way.

**Comment by tramvm** [comment]
You run the main function in PlayMain.java right?
So take some screenshot about: project structure, full path of opencv
folder and config of VM argument.

Thanks & best regards,

Vo Minh Tram

**Comment by rajesh-rt** [comment]
I created a class FaceRecognizer1.java that does the recognition process. Here is the VM argument:
-Djava.library.path="C:\opencv-2.4.11\opencv\build\java\x64; C:\opencv-2.4.11\opencv\build\java\x64\vc12\bin" 

OpenCV path - C:\opencv-2.4.11\opencv\build\java

**Comment by venky1311** [comment]
I am facing the same issue...please help to fix this issue.

@amzurrtalari1909 @vmtram 

Exception in thread "main" java.lang.UnsatisfiedLinkError: com.compa.opencv.nativec.FisherFaceRecognizerID.createFisherFaceRecognizer_0()J
	at com.compa.opencv.nativec.FisherFaceRecognizerID.createFisherFaceRecognizer_0(Native Method)
	at com.compa.opencv.nativec.FisherFaceRecognizerID.<init>(FisherFaceRecognizerID.java:16)
	at com.compa.opencv.PlayMain.createRecognizer(PlayMain.java:144)
	at com.compa.opencv.PlayMain.cameraRecognize(PlayMain.java:91)
	at com.compa.opencv.PlayMain.main(PlayMain.java:36)

**Comment by tramvm** [comment]
I have mention how to config OpenCv when run eclipse here: https://youtu.be/8zjFofbsJGM
It can help to resolve your problem.

**Comment by venky1311** [comment]
@vmtram 

 I have follow the steps but still facing the same issue.

please help

**Comment by tramvm** [comment]
Please refer this article to resolve the problem:
http://stackoverflow.com/questions/25830660/face-recognize-using-opencv4android-sdk-tutorial
Sorry. I lost this DLL, if have time I will build this DLL and publish here.

**Comment by KOR2017** [comment]
@vmtram Did you by any chance build the DLL file?

Thanks
